import React, { useState } from 'react';
import { City, TradeAnalysis, AppMode, TravelLogistics } from '../types';
import { CITIES, TRAVEL_SPEEDS, HISTORICAL_CONTEXT, DOMINANT_EMPIRES } from '../constants';

interface InfoPanelProps {
    mode: AppMode;
    setMode: (mode: AppMode) => void;
    selectedCities: string[];
    resetSelection: () => void;
    analysis: TradeAnalysis | null;
    logistics: TravelLogistics | null;
    isLoading: boolean;
    onPlotRoute: () => void;
    onManualSelect: (index: number, cityId: string) => void;
    onAddStop: () => void;
    onRemoveStop: (index: number) => void;
}

const InfoPanel: React.FC<InfoPanelProps> = ({ 
    mode, 
    setMode, 
    selectedCities, 
    resetSelection, 
    analysis,
    logistics,
    isLoading,
    onPlotRoute,
    onManualSelect,
    onAddStop,
    onRemoveStop
}) => {
    const [isContextOpen, setIsContextOpen] = useState(true);

    const getCityName = (id: string) => CITIES.find(c => c.id === id)?.name || id;

    const downloadReport = () => {
        if (!analysis || !logistics) return;
  
        const csvContent = [
          ['SILK ROAD TRADING MANIFEST', ''],
          ['GENERATED BY', 'SILK_ROAD_OS'],
          ['ERA', HISTORICAL_CONTEXT.ERA],
          ['TIMEFRAME', HISTORICAL_CONTEXT.TIMEFRAME],
          ['DATE', new Date().toISOString()],
          ['', ''],
          ['LOGISTICS DATA', ''],
          ['--------------------------', ''],
          ['ROUTE PATH', analysis.route],
          ['TOTAL DISTANCE', `${logistics.totalDistanceKm} km`],
          ['EST. TIME (FOOT)', `${logistics.daysByFoot} days`],
          ['EST. TIME (CARAVAN)', `${logistics.daysByCaravan} days`],
          ['EST. TIME (HORSE)', `${logistics.daysByHorse} days`],
          ['', ''],
          ['TRADE ANALYSIS', ''],
          ['--------------------------', ''],
          ['COMMODITIES', analysis.goods.join('; ')],
          ['POLITICAL RISKS', analysis.risks.join('; ')],
          ['DISEASE DEMOGRAPHY', analysis.diseases.join('; ')],
          ['ECONOMIC YIELD', analysis.benefits],
          ['HISTORICAL CONTEXT', analysis.historicalContext],
          ['', ''],
          ['CALCULATION BASIS', ''],
          ['METHOD', 'Haversine Formula (Great-Circle Distance)'],
          ['SPEED (FOOT)', `${TRAVEL_SPEEDS.FOOT} km/day`],
          ['SPEED (CARAVAN)', `${TRAVEL_SPEEDS.CARAVAN} km/day`],
          ['SPEED (HORSE)', `${TRAVEL_SPEEDS.HORSE} km/day`],
          ['', ''],
          ['BIBLIOGRAPHY', ''],
          ['SOURCE', 'Ziegler, J. (2020). ISE TRADITIONS & ENCOUNTERS : a global perspective on the past. McGraw Hill.']
        ].map(row => row.map(cell => `"${cell.toString().replace(/"/g, '""')}"`).join(",")).join("\n");
  
        const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.setAttribute('href', url);
        link.setAttribute('download', `SILK_ROAD_MANIFEST_${Date.now()}.csv`);
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    return (
        <div className="h-full w-full bg-white border-4 border-black p-4 flex flex-col shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] overflow-y-auto relative">
            
            {/* Header Controls */}
            <div className="flex flex-col gap-2 mb-6">
                <div className="text-xs font-bold uppercase tracking-widest text-gray-500 mb-1">System Mode</div>
                <div className="flex gap-2">
                    <button 
                        onClick={() => { setMode(AppMode.EXPLORE); resetSelection(); }}
                        className={`flex-1 py-3 px-2 font-bold text-sm uppercase border-2 border-black transition-all 
                            ${mode === AppMode.EXPLORE ? 'bg-black text-white' : 'bg-white text-black hover:bg-gray-100'}`}
                    >
                        [ Explore ]
                    </button>
                    <button 
                        onClick={() => { setMode(AppMode.PLOT_ROUTE); resetSelection(); }}
                        className={`flex-1 py-3 px-2 font-bold text-sm uppercase border-2 border-black transition-all 
                            ${mode === AppMode.PLOT_ROUTE ? 'bg-[#ff0000] text-white border-[#ff0000]' : 'bg-white text-black hover:bg-gray-100'}`}
                    >
                        [ Plot Route ]
                    </button>
                </div>
            </div>

            {/* Context Area */}
            <div className="flex-1 flex flex-col gap-4">
                
                {/* Historical Context Module */}
                <div className="border-2 border-black bg-gray-50">
                    <button 
                        onClick={() => setIsContextOpen(!isContextOpen)}
                        className="w-full flex justify-between items-center p-2 bg-gray-200 border-b-2 border-black hover:bg-gray-300"
                    >
                        <span className="font-black text-xs uppercase">Geo-Political Context</span>
                        <span className="font-mono font-bold">{isContextOpen ? '[-]' : '[+]'}</span>
                    </button>
                    
                    {isContextOpen && (
                        <div className="p-3 text-[11px] font-mono leading-tight animate-in slide-in-from-top-2">
                            <div className="mb-2">
                                <span className="font-bold">ERA:</span> {HISTORICAL_CONTEXT.ERA}<br/>
                                <span className="font-bold">TIMEFRAME:</span> {HISTORICAL_CONTEXT.TIMEFRAME}
                            </div>
                            <div className="mb-2 italic text-gray-600">
                                "{HISTORICAL_CONTEXT.DESCRIPTION}"
                            </div>
                            <div className="border-t border-black pt-2 mt-2">
                                <span className="font-bold block mb-1 bg-black text-white w-fit px-1">DOMINANT EMPIRES:</span>
                                <ul className="list-square list-inside text-gray-800">
                                    {DOMINANT_EMPIRES.map((emp, i) => (
                                        <li key={i} className="mb-0.5">> {emp}</li>
                                    ))}
                                </ul>
                            </div>
                            <div className="mt-2 pt-2 border-t border-gray-300 text-gray-500 text-[9px]">
                                REF: Ziegler, J. (2020). Traditions & Encounters.
                            </div>
                        </div>
                    )}
                </div>

                <div className="border-b-4 border-black pb-2 mt-2">
                    <h2 className="text-2xl font-black uppercase">Status Log</h2>
                </div>

                {mode === AppMode.EXPLORE && selectedCities.length === 0 && (
                    <p className="font-mono text-sm">
                        > WAITING FOR INPUT...<br/>
                        > SELECT A NODE ON THE GRID TO VIEW EMPIRE AFFILIATION & TRADE DATA.
                    </p>
                )}

                {/* City Details (Single Selection) */}
                {selectedCities.length === 1 && mode === AppMode.EXPLORE && (
                    <div className="animate-in fade-in slide-in-from-bottom-4 duration-300">
                        <div className="bg-black text-white p-4 mb-4 shadow-[4px_4px_0px_0px_rgba(100,100,100,1)]">
                            <h3 className="text-2xl md:text-3xl font-bold uppercase leading-none mb-2">{getCityName(selectedCities[0])}</h3>
                            <div className="flex flex-col gap-1">
                                <span className="text-xs uppercase bg-white text-black w-fit px-1 font-bold">
                                    {CITIES.find(c => c.id === selectedCities[0])?.region}
                                </span>
                                <span className="text-xs uppercase bg-[#ff0000] text-white w-fit px-1 font-bold">
                                    {CITIES.find(c => c.id === selectedCities[0])?.empire}
                                </span>
                            </div>
                        </div>
                        <div className="border-2 border-black p-4 text-sm">
                            <p className="mb-2 font-bold">> NODE ACTIVE</p>
                            <p className="text-gray-600">> Switch to Plot Mode to calculate trade logistics across imperial borders.</p>
                        </div>
                    </div>
                )}

                {/* Route Plotting UI */}
                {mode === AppMode.PLOT_ROUTE && (
                    <div className="flex flex-col gap-4">
                        {selectedCities.map((cityId, index) => (
                            <div key={index} className="flex flex-col gap-1 animate-in slide-in-from-left-2">
                                <div className="flex justify-between items-center">
                                    <label className={`text-xs font-bold uppercase px-1 w-fit text-white ${index === 0 ? 'bg-black' : index === selectedCities.length - 1 ? 'bg-[#ff0000]' : 'bg-gray-500'}`}>
                                        {index === 0 ? 'Origin' : index === selectedCities.length - 1 ? 'Destination' : `Waypoint ${index}`}
                                    </label>
                                    {selectedCities.length > 2 && (
                                        <button onClick={() => onRemoveStop(index)} className="text-xs font-bold underline hover:text-red-600">[REMOVE]</button>
                                    )}
                                </div>
                                <select 
                                    className="w-full border-2 border-black p-2 font-mono text-sm uppercase focus:outline-none focus:bg-gray-100"
                                    value={cityId}
                                    onChange={(e) => onManualSelect(index, e.target.value)}
                                >
                                    <option value="" disabled>[ SELECT CITY ]</option>
                                    {CITIES.map(city => (
                                        <option key={city.id} value={city.id} disabled={selectedCities.includes(city.id) && city.id !== cityId}>
                                            {city.name}
                                        </option>
                                    ))}
                                </select>
                                {index < selectedCities.length - 1 && (
                                    <div className="flex justify-center -my-2 z-10">
                                        <span className="text-xl font-bold bg-white px-1 text-gray-400">&darr;</span>
                                    </div>
                                )}
                            </div>
                        ))}

                        {selectedCities.length < 5 && (
                            <button 
                                onClick={onAddStop}
                                className="w-full py-2 border-2 border-dashed border-black text-gray-500 hover:text-black hover:border-solid font-bold text-xs uppercase"
                            >
                                + Add Waypoint
                            </button>
                        )}
                        
                        {selectedCities.length >= 2 && !isLoading && (
                            <button 
                                onClick={onPlotRoute}
                                className="w-full py-4 mt-4 bg-black text-white font-bold text-lg hover:bg-[#ff0000] transition-colors uppercase border-2 border-transparent hover:border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] active:translate-y-1 active:shadow-none"
                            >
                                {analysis ? 'Refresh Data' : 'Initialize Trade Calculation'}
                            </button>
                        )}
                    </div>
                )}

                {/* Logistics Data */}
                {logistics && (
                    <div className="mt-4 border-2 border-black p-3 bg-white">
                         <h4 className="font-black text-sm bg-gray-200 p-1 mb-2 inline-block border border-black">LOGISTICS DATA</h4>
                         <div className="grid grid-cols-2 gap-y-2 text-xs font-mono mb-3">
                            <div className="font-bold">TOTAL DISTANCE:</div>
                            <div className="text-right">{logistics.totalDistanceKm} KM</div>
                            
                            <div className="col-span-2 border-b border-black my-1 opacity-20"></div>
                            
                            <div>EST. BY FOOT:</div>
                            <div className="text-right">{logistics.daysByFoot} DAYS</div>
                            
                            <div>EST. BY CARAVAN:</div>
                            <div className="text-right">{logistics.daysByCaravan} DAYS</div>
                            
                            <div>EST. BY HORSE:</div>
                            <div className="text-right">{logistics.daysByHorse} DAYS</div>
                         </div>
                         
                         <div className="bg-gray-100 border-t border-black p-2 text-[10px] leading-tight text-gray-600 font-mono">
                            <strong>CALCULATION BASIS:</strong><br/>
                            > DISTANCE: HAVERSINE FORMULA.<br/>
                            > SPEEDS: FOOT ({TRAVEL_SPEEDS.FOOT}KM/D), CARAVAN ({TRAVEL_SPEEDS.CARAVAN}KM/D), HORSE ({TRAVEL_SPEEDS.HORSE}KM/D).<br/>
                         </div>
                    </div>
                )}

                {/* Analysis Output */}
                {isLoading && (
                    <div className="border-2 border-black p-4 bg-gray-100 mt-4">
                        <p className="animate-pulse font-mono text-sm font-bold">> COMPUTING LOGISTICS VIA GEMINI CORE...</p>
                    </div>
                )}

                {analysis && (
                    <div className="flex flex-col gap-4 animate-in zoom-in-95 duration-300 mt-2 mb-8">
                        <div className="bg-gray-100 border-2 border-black p-4 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
                            <h4 className="font-black text-lg border-b-2 border-black mb-2 pb-1">ROUTE MANIFEST</h4>
                            <p className="text-sm font-bold mb-4 break-words">{analysis.route}</p>
                            
                            <div className="grid grid-cols-1 gap-4 mb-4">
                                <div>
                                    <span className="text-xs font-bold bg-black text-white px-1">GOODS EXCHANGE</span>
                                    <ul className="text-xs list-disc list-inside mt-1">
                                        {analysis.goods.map((g, i) => <li key={i}>{g}</li>)}
                                    </ul>
                                </div>
                                <div>
                                    <span className="text-xs font-bold bg-[#ff0000] text-white px-1">HAZARDS</span>
                                    <ul className="text-xs list-disc list-inside mt-1">
                                        {analysis.risks.map((r, i) => <li key={i}>{r}</li>)}
                                    </ul>
                                </div>
                                <div>
                                    <span className="text-xs font-bold bg-yellow-400 text-black px-1 border border-black">DISEASE DEMOGRAPHY</span>
                                    <ul className="text-xs list-disc list-inside mt-1">
                                        {analysis.diseases.map((d, i) => <li key={i}>{d}</li>)}
                                    </ul>
                                </div>
                            </div>

                            <div className="mb-4">
                                <span className="text-xs font-bold bg-black text-white px-1">ECONOMIC YIELD</span>
                                <p className="text-sm mt-1 leading-tight">{analysis.benefits}</p>
                            </div>

                            <div className="mb-4">
                                <span className="text-xs font-bold bg-black text-white px-1">ARCHIVE DATA</span>
                                <p className="text-xs mt-1 text-gray-600 italic border-l-2 border-black pl-2">"{analysis.historicalContext}"</p>
                            </div>
                            
                            <button 
                                onClick={downloadReport}
                                className="w-full py-2 border-2 border-black bg-white hover:bg-black hover:text-white font-bold text-xs uppercase transition-colors"
                            >
                                [ DOWNLOAD REPORT.CSV ]
                            </button>
                        </div>
                        
                        <button 
                             onClick={resetSelection}
                             className="self-end text-xs font-bold underline hover:text-[#ff0000] p-2"
                        >
                            [ CLEAR DATA ]
                        </button>
                    </div>
                )}
                
                {/* Footer Citation (always visible at bottom of scroll if needed) */}
                 <div className="mt-auto pt-8 pb-4">
                    <h6 className="text-[10px] font-bold uppercase tracking-widest text-gray-400 mb-2 border-b border-gray-300 pb-1">
                        System Reference
                    </h6>
                    <div className="text-[10px] font-mono text-gray-600 bg-gray-50 p-2 border-l-2 border-gray-300">
                        <span className="font-bold text-black">SOURCE:</span> Ziegler, J. (2020). 
                        <br/><span className="italic">ISE TRADITIONS & ENCOUNTERS : a global perspective on the past.</span> 
                        <br/>McGraw Hill.
                    </div>
                </div>
            </div>

            {/* Footer */}
            <div className="mt-4 pt-4 border-t-4 border-black text-[10px] uppercase text-gray-500">
                SYS_VER: 2.2.0 // MILLENNIUM_ERA // 1000-1020_CE
            </div>
        </div>
    );
};

export default InfoPanel;